[[redirects]]
  from = "/projects/algo-sort/*"
  to = "https://algo-sort-zekave.netlify.app/algos/:splat"
  force = true
  status = 200
  [redirects.headers]
  X-From = "Netlify"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/projects"
  to = "/projects"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about"
  status = 200
